using System;
using System.Threading.Tasks;
using Examples;

namespace DotnetRaylibWasm;

public static class Program
{
    public static int Main(string[] args)
    {
        if (args.Length == 0)
        {
            return 0;
        }

        return args[0] switch
        {
            "ImageLoading" => Examples.Textures.ImageLoading.Main(),
            "SpriteExplosion" => Examples.Textures.SpriteExplosion.Main(),
            "ToImage" => Examples.Textures.ToImage.Main(),
            "SpriteButton" => Examples.Textures.SpriteButton.Main(),
            "ParticlesBlending" => Examples.Textures.ParticlesBlending.Main(),
            "NpatchDrawing" => Examples.Textures.NpatchDrawing.Main(),
            "SpriteAnim" => Examples.Textures.SpriteAnim.Main(),
            "BlendModes" => Examples.Textures.BlendModes.Main(),
            "SrcRecDstRec" => Examples.Textures.SrcRecDstRec.Main(),
            "MousePainting" => Examples.Textures.MousePainting.Main(),
            "Bunnymark" => Examples.Textures.Bunnymark.Main(),
            "ImageGeneration" => Examples.Textures.ImageGeneration.Main(),
            "RawData" => Examples.Textures.RawData.Main(),
            "BackgroundScrolling" => Examples.Textures.BackgroundScrolling.Main(),
            "ImageText" => Examples.Textures.ImageText.Main(),
            "ImageDrawing" => Examples.Textures.ImageDrawing.Main(),
            "ImageProcessing" => Examples.Textures.ImageProcessing.Main(),
            "LogoRaylibTexture" => Examples.Textures.LogoRaylibTexture.Main(),
            "InputBox" => Examples.Text.InputBox.Main(),
            "FormatText" => Examples.Text.FormatText.Main(),
            "RaylibFonts" => Examples.Text.RaylibFonts.Main(),
            "WritingAnim" => Examples.Text.WritingAnim.Main(),
            "RectangleBounds" => Examples.Text.RectangleBounds.Main(),
            "FontFilters" => Examples.Text.FontFilters.Main(),
            "FontLoading" => Examples.Text.FontLoading.Main(),
            "FontSdf" => Examples.Text.FontSdf.Main(),
            "FontSpritefont" => Examples.Text.FontSpritefont.Main(),
            "EasingsRectangleArray" => Examples.Shapes.EasingsRectangleArray.Main(),
            "LogoRaylibAnim" => Examples.Shapes.LogoRaylibAnim.Main(),
            "EasingsBoxAnim" => Examples.Shapes.EasingsBoxAnim.Main(),
            "DrawCircleSector" => Examples.Shapes.DrawCircleSector.Main(),
            "EasingsBallAnim" => Examples.Shapes.EasingsBallAnim.Main(),
            "LinesBezier" => Examples.Shapes.LinesBezier.Main(),
            "ColorsPalette" => Examples.Shapes.ColorsPalette.Main(),
            "DrawRectangleRounded" => Examples.Shapes.DrawRectangleRounded.Main(),
            "FollowingEyes" => Examples.Shapes.FollowingEyes.Main(),
            "CollisionArea" => Examples.Shapes.CollisionArea.Main(),
            "RectangleScaling" => Examples.Shapes.RectangleScaling.Main(),
            "BouncingBall" => Examples.Shapes.BouncingBall.Main(),
            "LogoRaylibShape" => Examples.Shapes.LogoRaylibShape.Main(),
            "BasicShapes" => Examples.Shapes.BasicShapes.Main(),
            "DrawRing" => Examples.Shapes.DrawRing.Main(),
            "TextureWaves" => Examples.Shaders.TextureWaves.Main(),
            "MultiSample2d" => Examples.Shaders.MultiSample2d.Main(),
            "Fog" => Examples.Shaders.Fog.Main(),
            "ShapesTextures" => Examples.Shaders.ShapesTextures.Main(),
            "CustomUniform" => Examples.Shaders.CustomUniform.Main(),
            "TextureDrawing" => Examples.Shaders.TextureDrawing.Main(),
            "PostProcessing" => Examples.Shaders.PostProcessing.Main(),
            "MeshInstancing" => Examples.Shaders.MeshInstancing.Main(),
            "PaletteSwitch" => Examples.Shaders.PaletteSwitch.Main(),
            "Eratosthenes" => Examples.Shaders.Eratosthenes.Main(),
            "HotReloading" => Examples.Shaders.HotReloading.Main(),
            "TextureOutline" => Examples.Shaders.TextureOutline.Main(),
            "Spotlight" => Examples.Shaders.Spotlight.Main(),
            "SimpleMask" => Examples.Shaders.SimpleMask.Main(),
            "JuliaSet" => Examples.Shaders.JuliaSet.Main(),
            "ModelShader" => Examples.Shaders.ModelShader.Main(),
            "BasicLighting" => Examples.Shaders.BasicLighting.Main(),
            "Raymarching" => Examples.Shaders.Raymarching.Main(),
            "SkyboxDemo" => Examples.Models.SkyboxDemo.Main(),
            "WavingCubes" => Examples.Models.WavingCubes.Main(),
            "HeightmapDemo" => Examples.Models.HeightmapDemo.Main(),
            "CubicmapDemo" => Examples.Models.CubicmapDemo.Main(),
            "MeshGeneration" => Examples.Models.MeshGeneration.Main(),
            "LoadingGltf" => Examples.Models.LoadingGltf.Main(),
            "LoadingDemo" => Examples.Models.LoadingDemo.Main(),
            "SolarSystem" => Examples.Models.SolarSystem.Main(),
            "AnimationDemo" => Examples.Models.AnimationDemo.Main(),
            "LoadingVox" => Examples.Models.LoadingVox.Main(),
            "GeometricShapes" => Examples.Models.GeometricShapes.Main(),
            "YawPitchRoll" => Examples.Models.YawPitchRoll.Main(),
            "OrthographicProjection" => Examples.Models.OrthographicProjection.Main(),
            "BoxCollisions" => Examples.Models.BoxCollisions.Main(),
            "BillboardDemo" => Examples.Models.BillboardDemo.Main(),
            "FirstPersonMaze" => Examples.Models.FirstPersonMaze.Main(),
            "SoundLoading" => Examples.Audio.SoundLoading.Main(),
            "MultichannelSound" => Examples.Audio.MultichannelSound.Main(),
            "ModulePlaying" => Examples.Audio.ModulePlaying.Main(),
            "MusicStreamDemo" => Examples.Audio.MusicStreamDemo.Main(),
            "RawStream" => Examples.Audio.RawStream.Main(),
            "Camera3dFirstPerson" => Examples.Core.Camera3dFirstPerson.Main(),
            "WorldScreen" => Examples.Core.WorldScreen.Main(),
            "ScissorTest" => Examples.Core.ScissorTest.Main(),
            "DropFiles" => Examples.Core.DropFiles.Main(),
            "VrSimulator" => Examples.Core.VrSimulator.Main(),
            "RandomValues" => Examples.Core.RandomValues.Main(),
            "InputKeys" => Examples.Core.InputKeys.Main(),
            "WindowFlags" => Examples.Core.WindowFlags.Main(),
            "SmoothPixelPerfect" => Examples.Core.SmoothPixelPerfect.Main(),
            "Picking3D" => Examples.Core.Picking3d.Main(),
            "Camera3dFree" => Examples.Core.Camera3dFree.Main(),
            "InputMultitouch" => Examples.Core.InputMultitouch.Main(),
            "Camera2dPlatformer" => Examples.Core.Camera2dPlatformer.Main(),
            "InputGestures" => Examples.Core.InputGestures.Main(),
            "InputMouseWheel" => Examples.Core.InputMouseWheel.Main(),
            "BasicWindow" => Examples.Core.BasicWindow.Main(),
            "WindowLetterbox" => Examples.Core.WindowLetterbox.Main(),
            "InputGamepad" => Examples.Core.InputGamepad.Main(),
            "Camera2dDemo" => Examples.Core.Camera2dDemo.Main(),
            "InputMouse" => Examples.Core.InputMouse.Main(),
            "BasicScreenManager" => Examples.Core.BasicScreenManager.Main(),
            "Camera3dMode" => Examples.Core.Camera3dMode.Main(),
            _ => throw new Exception("Not found?")
        };
    } 
}
